// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Handlers is an autogenerated mock type for the Handlers type
type Handlers struct {
	mock.Mock
}

// GetPresignedS3Url provides a mock function with given fields: w, r
func (_m *Handlers) GetPresignedS3Url(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UploadToS3 provides a mock function with given fields: w, r
func (_m *Handlers) UploadToS3(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewHandlers creates a new instance of Handlers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlers(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handlers {
	mock := &Handlers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
