// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UUIDUtil is an autogenerated mock type for the UUIDUtil type
type UUIDUtil struct {
	mock.Mock
}

// Generate provides a mock function with no fields
func (_m *UUIDUtil) Generate() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewUUIDUtil creates a new instance of UUIDUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUUIDUtil(t interface {
	mock.TestingT
	Cleanup(func())
}) *UUIDUtil {
	mock := &UUIDUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
